import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { Alert, Button, Card, Checkbox, Col, Descriptions, Empty, Form, Input, Layout, Menu, Modal, Row, Select, Space, Statistic, Table, Tag, Typography, Upload, message } from 'antd';
import type { UploadProps } from 'antd';
import { createPrediction, Dataset, getDatasets, getHealth, getJobs, getNotifications, getPredictionResults, getPredictions, getPredictionSummary, getStorePredictionSummary, Job, NotificationRecord, PredictionRun, PredictionSummary, predictionDownloadUrl, predictionExcelUrl, processDataset, sendPredictionNotification, sendTestEmail, uploadFile, UploadResult } from './lib/api';

const { Header, Sider, Content } = Layout;
type View = 'dashboard' | 'upload' | 'jobs' | 'datasets' | 'models' | 'prediction' | 'results' | 'notifications';
const mcLabels: Record<string, string> = { MC0: 'MC0（0）', MC1: 'MC1（1）', MC2: 'MC2（2–4）', MC3: 'MC3（5–19）', MC4: 'MC4（20+）' };
const status = (value: string) => <Tag color={{ SUCCESS: 'success', FAILED: 'error', RUNNING: 'processing', READY: 'success' }[value] || 'default'}>{value}</Tag>;
const fixed = (value: unknown) => typeof value === 'number' ? value.toFixed(4) : '—';

export default function App() {
  const [view, setView] = useState<View>('dashboard'); const [health, setHealth] = useState('loading'); const [jobs, setJobs] = useState<Job[]>([]); const [datasets, setDatasets] = useState<Dataset[]>([]); const [runs, setRuns] = useState<PredictionRun[]>([]);
  const refresh = async () => { try { const [h, j, d, r] = await Promise.all([getHealth(), getJobs(), getDatasets(), getPredictions()]); setHealth(h.status); setJobs(j.items); setDatasets(d.items); setRuns(r.items); } catch { setHealth('failed'); } };
  useEffect(() => { void refresh(); }, []);
  const pages: Record<View, ReactNode> = { dashboard: <Dashboard health={health} datasets={datasets} runs={runs} />, upload: <UploadPage refresh={refresh} />, jobs: <JobsPage jobs={jobs} />, datasets: <DatasetsPage datasets={datasets} />, models: <ModelsPage />, prediction: <PredictionPage datasets={datasets} refresh={refresh} />, results: <ResultsPage runs={runs} />, notifications: <NotificationsPage /> };
  return <Layout style={{ minHeight: '100vh' }}><Sider width={228} theme="dark"><div className="brand">文轩集团<br />图书销量预测系统</div><Menu theme="dark" mode="inline" selectedKeys={[view]} onClick={({ key }) => setView(key as View)} items={[['dashboard', 'Dashboard'], ['upload', '数据上传'], ['jobs', '任务中心'], ['datasets', '数据集管理'], ['models', '模型中心'], ['prediction', '预测'], ['results', '预测结果'], ['notifications', '通知设置']].map(([key, label]) => ({ key, label }))} /></Sider><Layout><Header style={{ background: '#fff', padding: '0 24px' }}><Space><Typography.Text strong>数据、预测与结果管理</Typography.Text>{status(health === 'ok' ? 'SUCCESS' : 'FAILED')}<Button onClick={() => void refresh()}>刷新</Button></Space></Header><Content className="content">{pages[view]}</Content></Layout></Layout>;
}

function Dashboard({ health, datasets, runs }: { health: string; datasets: Dataset[]; runs: PredictionRun[] }) { return <><h1 className="page-title">Dashboard</h1><Row gutter={16}><Col span={8}><Card><Statistic title="后端状态" value={health} /></Card></Col><Col span={8}><Card><Statistic title="数据集数" value={datasets.length} /></Card></Col><Col span={8}><Card><Statistic title="预测运行数" value={runs.length} /></Card></Col></Row></>; }
function UploadPage({ refresh }: { refresh: () => Promise<void> }) { const [upload, setUpload] = useState<UploadResult>(); const [form] = Form.useForm(); const [busy, setBusy] = useState(false); const props: UploadProps = { accept: '.csv,.zip', beforeUpload: async f => { try { setUpload(await uploadFile(f)); message.success('上传完成'); } catch (e) { message.error(String(e)); } return false; }, maxCount: 1 }; const process = async () => { if (!upload) return; const values = await form.validateFields(); setBusy(true); try { await processDataset(upload.upload_id, values.name); await refresh(); message.success('处理任务已创建'); } finally { setBusy(false); } }; return <><h1 className="page-title">数据上传</h1><Card><Upload.Dragger {...props}><p>点击或拖拽上传 CSV / ZIP</p></Upload.Dragger>{upload && <Form form={form} layout="inline" style={{ marginTop: 16 }}><Form.Item name="name" rules={[{ required: true }]}><Input placeholder="数据集名称" /></Form.Item><Button type="primary" loading={busy} disabled={upload.mapping_status !== 'READY'} onClick={() => void process()}>开始处理</Button></Form>}</Card></>; }
function JobsPage({ jobs }: { jobs: Job[] }) { return <><h1 className="page-title">任务中心</h1><Table rowKey="job_id" dataSource={jobs} columns={[{ title: '任务 ID', dataIndex: 'job_id' }, { title: '类型', dataIndex: 'job_type' }, { title: '状态', dataIndex: 'status', render: status }, { title: '错误', dataIndex: 'error_message' }]} /></>; }
function DatasetsPage({ datasets }: { datasets: Dataset[] }) { return <><h1 className="page-title">数据集管理</h1><Table rowKey="dataset_id" dataSource={datasets} columns={[{ title: '名称', dataIndex: 'dataset_name' }, { title: '门店数', dataIndex: 'store_count' }, { title: '图书数', dataIndex: 'item_count' }, { title: '状态', dataIndex: 'status', render: status }, { title: '特征文件', dataIndex: 'feature_parquet_path' }]} /></>; }
function ModelsPage() { return <><h1 className="page-title">模型中心</h1><Row gutter={16}><Col span={8}><Card title="E0">基础 Two-stage，对照模型。</Card></Col><Col span={8}><Card title="E2">Cross-store 跨门店特征模型，推荐用于中高需求识别。</Card></Col><Col span={8}><Card title="E3">Diff + Cross-store，推荐用于总量控制优先。</Card></Col></Row><Alert style={{ marginTop: 16 }} type="info" message="Cross-store 使用说明" description="当前 E2 / E3 使用集中式 Cross-store 特征。单店上传、本店数据与总部汇总摘要组合预测属于后续 V2。" /><Alert style={{ marginTop: 12 }} type="warning" message="2M 状态" description="当前只接入正式 1M 模型；2M 待确认正式模型文件后接入。" /></>; }
function PredictionPage({ datasets, refresh }: { datasets: Dataset[]; refresh: () => Promise<void> }) { const [form] = Form.useForm(); const [busy, setBusy] = useState(false); const ready = datasets.filter(d => d.status === 'READY'); const submit = async () => { const values = await form.validateFields(); setBusy(true); try { await createPrediction({ dataset_id: values.dataset_id, model_ids: values.model_ids, observation_month: values.observation_month || undefined }); await refresh(); message.success('预测完成，已生成结果'); } catch (e) { message.error(String(e)); } finally { setBusy(false); } }; return <><h1 className="page-title">生成预测</h1><Card>{ready.length ? <Form form={form} layout="vertical" initialValues={{ model_ids: ['E2'] }}><Form.Item name="dataset_id" label="READY 数据集" rules={[{ required: true }]}><Select options={ready.map(d => ({ value: d.dataset_id, label: d.dataset_name }))} /></Form.Item><Form.Item name="model_ids" label="模型" rules={[{ required: true }]}><Checkbox.Group options={['E0', 'E2', 'E3']} /></Form.Item><Form.Item name="observation_month" label="Observation month"><Input placeholder="YYYY-MM（默认最新月份）" /></Form.Item><Button type="primary" loading={busy} onClick={() => void submit()}>开始预测</Button></Form> : <Empty description="暂无 READY 数据集" />}</Card></>; }

function NotificationButton({ run, modelId, siteNo, mc }: { run: PredictionRun; modelId: string; siteNo?: string; mc?: string }) { const [open, setOpen] = useState(false); const [email, setEmail] = useState(''); const [includeExcel, setIncludeExcel] = useState(true); const [busy, setBusy] = useState(false); const send = async () => { setBusy(true); try { const record = await sendPredictionNotification(run.prediction_run_id, { target_email: email, model_id: modelId, site_no: siteNo, mc, include_excel_link: includeExcel }); record.status === 'SUCCESS' ? message.success('邮件已发送') : message.error(record.error_message || '邮件发送失败'); setOpen(false); } catch (e) { message.error(String(e)); } finally { setBusy(false); } }; return <><Button onClick={() => setOpen(true)}>发送预测结果邮件</Button><Modal title="发送预测结果邮件" open={open} onCancel={() => setOpen(false)} onOk={() => void send()} okButtonProps={{ loading: busy, disabled: !email }}><Input value={email} onChange={e => setEmail(e.target.value)} placeholder="收件邮箱" /><Checkbox checked={includeExcel} onChange={e => setIncludeExcel(e.target.checked)} style={{ marginTop: 16 }}>包含 Excel 导出链接</Checkbox></Modal></>; }

function ResultsPage({ runs }: { runs: PredictionRun[] }) {
  const [run, setRun] = useState<PredictionRun>(); const [summary, setSummary] = useState<PredictionSummary>(); const [model, setModel] = useState(''); const [site, setSite] = useState(''); const [mc, setMc] = useState<string>(); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1);
  const load = async (nextRun: PredictionRun, nextModel: string, nextPage = 1, nextSite = site, nextMc = mc) => { const filters = { modelId: nextModel, siteNo: nextSite || undefined, mc: nextMc }; const [s, r] = await Promise.all([getPredictionSummary(nextRun.prediction_run_id, filters), getPredictionResults(nextRun.prediction_run_id, 'predictions', { ...filters, page: nextPage, pageSize: 50 })]); setRun(nextRun); setSummary(s); setModel(nextModel); setRows(r.items); setTotal(r.total); setPage(nextPage); };
  const current = summary?.filtered_summary; const filterDescription = `模型 ${model || '全部'}；门店 ${site || '全部'}；MC ${mc ? mcLabels[mc] : '全部'}`;
  const columns = [{ title: 'site_no', dataIndex: 'site_no' }, { title: 'item_id', dataIndex: 'item_id' }, { title: 'book_name', dataIndex: 'book_name' }, { title: '预测销量', dataIndex: 'pred_qty_int' }, { title: 'MC', dataIndex: 'pred_mc', render: (v: string) => mcLabels[v] || v }, { title: 'p_sale', dataIndex: 'p_sale', render: fixed }, { title: 'conditional_qty', dataIndex: 'conditional_qty', render: fixed }];
  return <><h1 className="page-title">预测结果</h1><Card title="预测运行"><Table rowKey="prediction_run_id" dataSource={runs} columns={[{ title: 'Run ID', dataIndex: 'prediction_run_id' }, { title: '模型', dataIndex: 'model_ids', render: (v: string[]) => v.join(' / ') }, { title: '状态', dataIndex: 'status', render: status }]} onRow={r => ({ onClick: () => { setSite(''); setMc(undefined); void load(r, r.model_ids[0], 1, '', undefined); } })} /></Card>{run && summary && <><Card style={{ marginTop: 16 }} title={run.prediction_run_id} extra={<Space><Button href={predictionDownloadUrl(run.prediction_run_id)}>下载完整 Parquet</Button><Button href={predictionExcelUrl(run.prediction_run_id, { modelId: model, siteNo: site || undefined, mc, includePredictions: Boolean(site), topN: 100 })}>按当前筛选导出 Excel</Button><NotificationButton run={run} modelId={model} siteNo={site || undefined} mc={mc} /></Space>}><Space wrap><Select value={model} onChange={v => void load(run, v)} options={summary.model_ids.map(v => ({ value: v, label: v }))} /><Input value={site} onChange={e => setSite(e.target.value)} placeholder="site_no" /><Select allowClear value={mc} onChange={setMc} placeholder="MC 等级" options={Object.entries(mcLabels).map(([value, label]) => ({ value, label }))} /><Button onClick={() => void load(run, model, 1)}>筛选</Button></Space><Alert style={{ marginTop: 16 }} type="info" message="当前筛选结果" description={filterDescription} />{current && <Row gutter={[12, 12]} style={{ marginTop: 16 }}><Col span={6}><Statistic title="预测总销量" value={current.prediction_total} /></Col><Col span={6}><Statistic title="有动销图书数" value={current.predicted_nonzero_book_count} /></Col><Col span={6}><Statistic title="覆盖门店数" value={current.store_count} /></Col><Col span={6}><Statistic title="覆盖图书数" value={current.item_count} /></Col>{Object.entries(mcLabels).map(([level, label]) => <Col span={4} key={level}><Statistic title={label} value={current.mc_counts[level] || 0} valueStyle={level === 'MC3' ? { color: '#d48806' } : level === 'MC4' ? { color: '#cf1322' } : undefined} /></Col>)}</Row>}</Card><Card style={{ marginTop: 16 }} title="预测图书明细"><Table rowKey={r => `${r.site_no}-${r.item_id}`} dataSource={rows} columns={columns} pagination={{ current: page, pageSize: 50, total, onChange: p => void load(run, model, p) }} /></Card></>}</>;
}

function NotificationsPage() { const [email, setEmail] = useState(''); const [records, setRecords] = useState<NotificationRecord[]>([]); const [busy, setBusy] = useState(false); const refresh = async () => setRecords((await getNotifications()).items); useEffect(() => { void refresh(); }, []); const send = async () => { setBusy(true); try { const result = await sendTestEmail(email); result.status === 'SUCCESS' ? message.success('测试邮件已发送') : message.error(result.error_message || '邮件发送失败'); await refresh(); } catch (e) { message.error(String(e)); } finally { setBusy(false); } }; return <><h1 className="page-title">通知设置</h1><Alert type="info" showIcon message="SMTP 配置说明" description="在后端环境变量或 software/config/app.yaml 配置 SMTP_HOST、SMTP_PORT、SMTP_USER、SMTP_PASSWORD、SMTP_FROM、SMTP_USE_TLS。密码仅通过环境变量提供。" /><Card style={{ marginTop: 16 }} title="发送测试邮件"><Space><Input value={email} onChange={e => setEmail(e.target.value)} placeholder="收件邮箱" /><Button type="primary" loading={busy} disabled={!email} onClick={() => void send()}>发送测试邮件</Button></Space></Card><Card style={{ marginTop: 16 }} title="最近通知" extra={<Button onClick={() => void refresh()}>刷新</Button>}><Table rowKey="notification_id" dataSource={records} columns={[{ title: '类型', dataIndex: 'type' }, { title: '收件人', dataIndex: 'target_email' }, { title: '状态', dataIndex: 'status', render: status }, { title: '关联 Run', dataIndex: 'related_run_id' }, { title: '错误', dataIndex: 'error_message' }]} /></Card></>; }
